//------------------------------------------------------------------------------
//                                           (c) корпорация ГАЛАКТИКА
// Версия        : 5.73
// Назначение    : Отчет о работе юридической службы  по взысканию убытков  по
//                 наименованию статуса документа
//------------------------------------------------------------------------------
#doc
<p>Отчет о работе юридической службы по взысканию убытков по наименованию статуса документа
#end
.form Otchet10
.p 60
.DEFO LANDSCAPE
.hide
.fields
 Otch1
 NSDoc
 NDoc
 period
 Nam
.endfields
^^^^^
.{ Otdelen10 CheckEnter
.[h

.]h
.fields
 f1:string
 f2:double
 f3:double
 f4:double
 f5:double
 f6:double
 f7:double
 f8:double
 f9:double
 f10:double
 f11:double
 f12:double
 f13:double
.endfields
^^^^^^^^^^^^^
.}
.fields
 fS1:double
 fS2:double
 fS3:double
 fS4:double
 fS5:double
 fS6:double
 fS7:double
 fS8:double
 fS9:double
 fS10:double
 fS11:double
 fS12:double
.endfields
^^^^^^^^^^^^
.endform