//------------------------------------------------------------------------------
//                                                      (c) корпорация Галактика
// Галактика 5.80 - модуль "Контроллинг"
// Форма печати : "Протокол формирования первичных документов"
//------------------------------------------------------------------------------

#doc
Форма печати : "Протокол формирования первичных документов"
#end
.set name='ProtErrMCExtKSService'
.hide
.fields
  OperationError

.endfields
 ^
.endform


.linkform 'ProtErrMCExtKSService1' prototype is 'ProtErrMCExtKSService'
.Nameinlist 'Протокол формирования первичных документов'
.fields
  OperationError

.endfields
 ^
.endform
