/*
   =====================================================================
  │      Н Т О  "T O P   S O F T",  А О   "Н О В Ы Й   А Т Л А Н Т"     │
  │      Проект    : ГАЛАКТИКА  (с) 2000                                │
  │      Система   : Управление персоналом                              │
  │      Версия    : 5.8                                                │
  │      Разработал: Антонович А.К.     03/08/2001                      │
  │      Назначение:                                                    │
  │      Изменения :                                                    │
   =====================================================================
*/

#doc
Форма 25
#end
.form FORM_25
.Hide

.Fields

DatePrikaz
NumPrikaz
OtchYear
OrgName

Count_T1_1
Count_T1_2
Count_T1_3
Count_T1_4
Count_T1_5
Count_T1_6
Count_T1_7
Count_T1_8
Count_T1_9
Count_T1_10
Count_T1_11
Count_T1_12
Count_T1_13
Count_T1_14
Count_T1_15
Count_T1_16

Count_T2_01_1
Count_T2_01_2
Count_T2_01_3
Count_T2_01_4
Count_T2_01_5
Count_T2_01_6
Count_T2_01_7
Count_T2_02_1
Count_T2_02_2
Count_T2_02_3
Count_T2_02_4
Count_T2_02_5
Count_T2_02_6
Count_T2_02_7
Count_T2_03_1
Count_T2_03_2
Count_T2_03_3
Count_T2_03_4
Count_T2_03_5
Count_T2_03_6
Count_T2_03_7
Count_T2_04_1
Count_T2_04_2
Count_T2_04_3
Count_T2_04_4
Count_T2_04_5
Count_T2_04_6
Count_T2_04_7
Count_T2_05_1
Count_T2_05_2
Count_T2_05_3
Count_T2_05_4
Count_T2_05_5
Count_T2_05_6
Count_T2_05_7
Count_T2_06_1
Count_T2_06_2
Count_T2_06_3
Count_T2_06_4
Count_T2_06_5
Count_T2_06_6
Count_T2_06_7
Count_T2_07_1
Count_T2_07_2
Count_T2_07_3
Count_T2_07_4
Count_T2_07_5
Count_T2_07_6
Count_T2_07_7
Count_T2_08_1
Count_T2_08_2
Count_T2_08_3
Count_T2_08_4
Count_T2_08_5
Count_T2_08_6
Count_T2_08_7
Count_T2_09_1
Count_T2_09_2
Count_T2_09_3
Count_T2_09_4
Count_T2_09_5
Count_T2_09_6
Count_T2_09_7
Count_T2_10_1
Count_T2_10_2
Count_T2_10_3
Count_T2_10_4
Count_T2_10_5
Count_T2_10_6
Count_T2_10_7
Count_T2_11_1
Count_T2_11_2
Count_T2_11_3
Count_T2_11_4
Count_T2_11_5
Count_T2_11_6
Count_T2_11_7
Count_T2_12_1
Count_T2_12_2
Count_T2_12_3
Count_T2_12_4
Count_T2_12_5
Count_T2_12_6
Count_T2_12_7
Count_T2_13_1
Count_T2_13_2
Count_T2_13_3
Count_T2_13_4
Count_T2_13_5
Count_T2_13_6
Count_T2_13_7
Count_T2_14_1
Count_T2_14_2
Count_T2_14_3
Count_T2_14_4
Count_T2_14_5
Count_T2_14_6
Count_T2_14_7
Count_T2_15_1
Count_T2_15_2
Count_T2_15_3
Count_T2_15_4
Count_T2_15_5
Count_T2_15_6
Count_T2_15_7
Count_T2_16_1
Count_T2_16_2
Count_T2_16_3
Count_T2_16_4
Count_T2_16_5
Count_T2_16_6
Count_T2_16_7
Count_T2_17_1
Count_T2_17_2
Count_T2_17_3
Count_T2_17_4
Count_T2_17_5
Count_T2_17_6
Count_T2_17_7
Count_T2_18_1
Count_T2_18_2
Count_T2_18_3
Count_T2_18_4
Count_T2_18_5
Count_T2_18_6
Count_T2_18_7
Count_T2_19_1
Count_T2_19_2
Count_T2_19_3
Count_T2_19_4
Count_T2_19_5
Count_T2_19_6
Count_T2_19_7
Count_T2_20_1
Count_T2_20_2
Count_T2_20_3
Count_T2_20_4
Count_T2_20_5
Count_T2_20_6
Count_T2_20_7

payEduc

Count_T3_01_1
Count_T3_01_2
Count_T3_01_3
Count_T3_02_1
Count_T3_02_2
Count_T3_02_3
Count_T3_03_1
Count_T3_03_2
Count_T3_03_3
Count_T3_04_1
Count_T3_04_2
Count_T3_04_3
Count_T3_05_1
Count_T3_05_2
Count_T3_05_3
Count_T3_06_1
Count_T3_06_2
Count_T3_06_3
Count_T3_07_1
Count_T3_07_2
Count_T3_07_3
Count_T3_08_1
Count_T3_08_2
Count_T3_08_3

countAll

CurDate
ExecutFIO
BossFIO

.endFields

DatePrikaz             ^
NumPrikaz              ^
OtchYear               ^
OrgName                ^

Count_T1_1-_16 (16 шт) ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^

Count_T2_01_1 (7 x 20) ^ ^ ^ ^ ^ ^ ^
                       ^ ^ ^ ^ ^ ^ ^
                       ^ ^ ^ ^ ^ ^ ^
                       ^ ^ ^ ^ ^ ^ ^
                       ^ ^ ^ ^ ^ ^ ^
                       ^ ^ ^ ^ ^ ^ ^
                       ^ ^ ^ ^ ^ ^ ^
                       ^ ^ ^ ^ ^ ^ ^
                       ^ ^ ^ ^ ^ ^ ^
                       ^ ^ ^ ^ ^ ^ ^
                       ^ ^ ^ ^ ^ ^ ^
                       ^ ^ ^ ^ ^ ^ ^
                       ^ ^ ^ ^ ^ ^ ^
                       ^ ^ ^ ^ ^ ^ ^
                       ^ ^ ^ ^ ^ ^ ^
                       ^ ^ ^ ^ ^ ^ ^
                       ^ ^ ^ ^ ^ ^ ^
                       ^ ^ ^ ^ ^ ^ ^
                       ^ ^ ^ ^ ^ ^ ^
                       ^ ^ ^ ^ ^ ^ ^

payEduc                ^

Count_T3_01_1 (3 x 8)  ^ ^ ^
                       ^ ^ ^
                       ^ ^ ^
                       ^ ^ ^
                       ^ ^ ^
                       ^ ^ ^
                       ^ ^ ^
                       ^ ^ ^

countAll               ^

CurDate                ^
ExecutFIO              ^
BossFIO                ^

.endform