/*
  ษอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
  บ       ’   "T O P   S O F T",  €    "       € ’  €  ’"     บ
  บ      เฎฅชโ    : €€’€  (แ) 2000                                บ
  บ      ‘จแโฅฌ    : “ฏเ ขซฅญจฅ ฏฅเแฎญ ซฎฌ                              บ
  บ      ฅเแจ๏    : 5.8, 7.1                                           บ
  บ       งเ กฎโ ซ: ฅซฅๅ   .….                                       บ
  บ       งญ ็ฅญจฅ: โ็ฅโ:  ็จแซฅญญฎแโจ, แฎแโ ขฅ จ ฎกใ็ฅญจจ ช คเฎข    บ
  บ      งฌฅญฅญจ๏ :                                                    บ
  ศอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
*/

#doc
โ็ฅโ:  ็จแซฅญญฎแโจ, แฎแโ ขฅ จ ฎกใ็ฅญจจ ช คเฎข
#end
.form Form6TN
.hide
.fields
Year
OrgName
ParentOrgName
เฃ ญ“ฏเ
”ฎเฌ ‘ฎกแโข
Adres



‘“
X

‘€’
”‘
”
!--------------------------------------------------------
AllNumPerson_3
AllNumPerson_4
AllNumPerson_5
AllNumPerson_6
AllNumPerson_7
AllNumPerson_8
!-------------------------------
Edu_High_3
Edu_High_4
Edu_High_5
Edu_High_6
Edu_High_7
Edu_High_8
!-------------------------------
Edu_MidSpecial_3
Edu_MidSpecial_4
Edu_MidSpecial_5
Edu_MidSpecial_6
Edu_MidSpecial_7
Edu_MidSpecial_8
!-------------------------------
ProfTechnikEdu_3
ProfTechnikEdu_4
ProfTechnikEdu_5
ProfTechnikEdu_6
ProfTechnikEdu_7
ProfTechnikEdu_8
!-------------------------------
Edu_Mid_3
Edu_Mid_4
Edu_Mid_5
Edu_Mid_6
Edu_Mid_7
Edu_Mid_8
!-------------------------------
Edu_Base_3
Edu_Base_4
Edu_Base_5
Edu_Base_6
Edu_Base_7
Edu_Base_8
!-------------------------------
Age_Before16_5:word
Age_Before16_6:word
Age_Before16_7:word
Age_Before16_8:word
!------------------------------
Age_16_24_3:word
Age_16_24_4:word
Age_16_24_5:word
Age_16_24_6:word
Age_16_24_7:word
Age_16_24_8:word
!------------------------------
Age_25_29_3:word
Age_25_29_4:word
Age_25_29_5:word
Age_25_29_6:word
Age_25_29_7:word
Age_25_29_8:word
!------------------------------
Age_30_3:word
Age_30_4:word
Age_30_5:word
Age_30_6:word
Age_30_7:word
Age_30_8:word
!------------------------------
Age_31_3:word
Age_31_4:word
Age_31_5:word
Age_31_6:word
Age_31_7:word
Age_31_8:word
!------------------------------
Age_32_39_3:word
Age_32_39_4:word
Age_32_39_5:word
Age_32_39_6:word
Age_32_39_7:word
Age_32_39_8:word
!------------------------------
Age_40_49_3:word
Age_40_49_4:word
Age_40_49_5:word
Age_40_49_6:word
Age_40_49_7:word
Age_40_49_8:word
!------------------------------
Age_50_54_3:word
Age_50_54_4:word
Age_50_54_5:word
Age_50_54_6:word
Age_50_54_7:word
Age_50_54_8:word
!------------------------------
Age_Older_55_3:word
Age_Older_55_4:word
Age_Older_55_5:word
Age_Older_55_6:word
Age_Older_55_7:word
Age_Older_55_8:word
!------------------------------
Wman_55_older_3:word
Wman_55_older_4:word
Wman_55_older_5:word
Wman_55_older_6:word
Wman_55_older_7:word
!------------------------------
Man_60_older_3:word
Man_60_older_4:word
Man_60_older_5:word
Man_60_older_6:word
Man_60_older_7:word
!------------------------------
WmanAtAll_3:word
WmanAtAll_4:word
WmanAtAll_5:word
WmanAtAll_6:word
WmanAtAll_7:word
!-------------------------------
ChildVacations
MChildVacations
PensOnWork
KidsOnWork
!-------------------------------
!-------- โ กซจๆ  2 ----------
SpecCnt_21_1:word  SpecCnt_21_2:word
SpecCnt_22_1:word  SpecCnt_22_2:word
SpecCnt_23_1:word  SpecCnt_23_2:word
SpecCnt_25_1:word  SpecCnt_25_2:word
SpecCnt_26_1:word  SpecCnt_26_2:word
SpecCnt_27_1:word  SpecCnt_27_2:word
SpecCnt_28_1:word  SpecCnt_28_2:word
SpecCnt_29_1:word  SpecCnt_29_2:word
SpecCnt_30_1:word  SpecCnt_30_2:word
SpecCnt_31_1:word  SpecCnt_31_2:word
SpecCnt_33_1:word  SpecCnt_33_2:word
SpecCnt_34_1:word  SpecCnt_34_2:word
SpecCnt_35_1:word  SpecCnt_35_2:word
SpecCnt_36_1:word  SpecCnt_36_2:word
SpecCnt_37_1:word  SpecCnt_37_2:word
SpecCnt_38_1:word  SpecCnt_38_2:word
SpecCnt_39_1:word  SpecCnt_39_2:word
SpecCnt_40_1:word  SpecCnt_40_2:word
SpecCnt_41_1:word  SpecCnt_41_2:word
SpecCnt_42_1:word  SpecCnt_42_2:word
SpecCnt_43_1:word  SpecCnt_43_2:word
SpecCnt_44_1:word  SpecCnt_44_2:word
SpecCnt_45_1:word  SpecCnt_45_2:word
SpecCnt_46_1:word  SpecCnt_46_2:word
SpecCnt_47_1:word  SpecCnt_47_2:word
SpecCnt_48_1:word  SpecCnt_48_2:word
SpecCnt_49_1:word  SpecCnt_49_2:word
SpecCnt_50_1:word  SpecCnt_50_2:word
SpecCnt_51_1:word  SpecCnt_51_2:word
SpecCnt_52_1:word  SpecCnt_52_2:word
SpecCnt_53_1:word  SpecCnt_53_2:word
SpecCnt_54_1:word  SpecCnt_54_2:word
SpecCnt_55_1:word  SpecCnt_55_2:word
SpecCnt_56_1:word  SpecCnt_56_2:word
SpecCnt_57_1:word  SpecCnt_57_2:word
SpecCnt_58_1:word  SpecCnt_58_2:word
CandidateOfScience:word
CandidateOfScience_w:word
DoctorofScience:word
DoctorofScience_w:word
!-------- โ กซจๆ  3 ----------
HighKval_3:word
HighKval_4:word
HighKval_5:word
HighKval_6:word
HighKval_7:word
HighKval_8:word

Stager_3:word
Stager_4:word
Stager_5:word
Stager_6:word
Stager_7:word
Stager_8:word

LernInFirst_3:word
LernInFirst_4:word
LernInFirst_5:word
LernInFirst_6:word
LernInFirst_7:word
LernInFirst_8:word

SmegProf_3:word
SmegProf_4:word
SmegProf_5:word
SmegProf_6:word
SmegProf_7:word
SmegProf_8:word

Perepodgotov_3:word
Perepodgotov_4:word
Perepodgotov_5:word
Perepodgotov_6:word
Perepodgotov_7:word
Perepodgotov_8:word

OutThereHighKval_3:word
OutThereHighKval_4:word
OutThereHighKval_5:word
OutThereHighKval_6:word
OutThereHighKval_7:word
OutThereHighKval_8:word

OutThereStager_3:word
OutThereStager_4:word
OutThereStager_5:word
OutThereStager_6:word
OutThereStager_7:word
OutThereStager_8:word

OutProf_3:word
OutProf_4:word
OutProf_5:word
OutProf_6:word
OutProf_7:word
OutProf_8:word
BossFio
FIO_isp
isp_posittion
isp_fone
FormDate
.endfields
^^^^^^^^^^^^^^

AllNumPerson_3                 ^
AllNumPerson_4                 ^
AllNumPerson_5                 ^
AllNumPerson_6                 ^
AllNumPerson_7                 ^
AllNumPerson_8                 ^
!-------------------------------
Edu_High_3                     ^
Edu_High_4                     ^
Edu_High_5                     ^
Edu_High_6                     ^
Edu_High_7                     ^
Edu_High_8                     ^
!-------------------------------
Edu_MidSpecial_3               ^
Edu_MidSpecial_4               ^
Edu_MidSpecial_5               ^
Edu_MidSpecial_6               ^
Edu_MidSpecial_7               ^
Edu_MidSpecial_8               ^
!-------------------------------
ProfTechnikEdu_3               ^
ProfTechnikEdu_4               ^
ProfTechnikEdu_5               ^
ProfTechnikEdu_6               ^
ProfTechnikEdu_7               ^
ProfTechnikEdu_8               ^
!-------------------------------
Edu_Mid_3                      ^
Edu_Mid_4                      ^
Edu_Mid_5                      ^
Edu_Mid_6                      ^
Edu_Mid_7                      ^
Edu_Mid_8                      ^
!-------------------------------
Edu_Base_3                     ^
Edu_Base_4                     ^
Edu_Base_5                     ^
Edu_Base_6                     ^
Edu_Base_7                     ^
Edu_Base_8                     ^
!-------------------------------
Age_Before16_5                 ^
Age_Before16_6                 ^
Age_Before16_7                 ^
Age_Before16_8                 ^
!-------------------------------
Age_16_24_3                    ^
Age_16_24_4                    ^
Age_16_24_5                    ^
Age_16_24_6                    ^
Age_16_24_7                    ^
Age_16_24_8                    ^
!-------------------------------
Age_25_29_3                    ^
Age_25_29_4                    ^
Age_25_29_5                    ^
Age_25_29_6                    ^
Age_25_29_7                    ^
Age_25_29_8                    ^
!-------------------------------
Age_30_3                       ^
Age_30_4                       ^
Age_30_5                       ^
Age_30_6                       ^
Age_30_7                       ^
Age_30_8                       ^
!-------------------------------
Age_31_3                       ^
Age_31_4                       ^
Age_31_5                       ^
Age_31_6                       ^
Age_31_7                       ^
Age_31_8                       ^
!-------------------------------
Age_32_39_3                    ^
Age_32_39_4                    ^
Age_32_39_5                    ^
Age_32_39_6                    ^
Age_32_39_7                    ^
Age_32_39_8                    ^
!-------------------------------
Age_40_49_3                    ^
Age_40_49_4                    ^
Age_40_49_5                    ^
Age_40_49_6                    ^
Age_40_49_7                    ^
Age_40_49_8                    ^
!-------------------------------
Age_50_54_3                    ^
Age_50_54_4                    ^
Age_50_54_5                    ^
Age_50_54_6                    ^
Age_50_54_7                    ^
Age_50_54_8                    ^
!-------------------------------
Age_Older_55_3                 ^
Age_Older_55_4                 ^
Age_Older_55_5                 ^
Age_Older_55_6                 ^
Age_Older_55_7                 ^
Age_Older_55_8                 ^
!-------------------------------
Wman_55_older_3                ^
Wman_55_older_4                ^
Wman_55_older_5                ^
Wman_55_older_6                ^
Wman_55_older_7                ^
!-------------------------------
Man_60_older_3                 ^
Man_60_older_4                 ^
Man_60_older_5                 ^
Man_60_older_6                 ^
Man_60_older_7                 ^
!-------------------------------
WmanAtAll_3                    ^
WmanAtAll_4                    ^
WmanAtAll_5                    ^
WmanAtAll_6                    ^
WmanAtAll_7                    ^
!-------------------------------
ChildVacations                 ^
MChildVacations                ^
PensOnWork                     ^
KidsOnWork                     ^
!-------------------------------
! table 2
SpecCnt_21_1:^  SpecCnt_21_2:^
SpecCnt_22_1:^  SpecCnt_22_2:^
SpecCnt_23_1:^  SpecCnt_23_2:^
SpecCnt_25_1:^  SpecCnt_25_2:^
SpecCnt_26_1:^  SpecCnt_26_2:^
SpecCnt_27_1:^  SpecCnt_27_2:^
SpecCnt_28_1:^  SpecCnt_28_2:^
SpecCnt_29_1:^  SpecCnt_29_2:^
SpecCnt_30_1:^  SpecCnt_30_2:^
SpecCnt_31_1:^  SpecCnt_31_2:^
SpecCnt_33_1:^  SpecCnt_33_2:^
SpecCnt_34_1:^  SpecCnt_34_2:^
SpecCnt_35_1:^  SpecCnt_35_2:^
SpecCnt_36_1:^  SpecCnt_36_2:^
SpecCnt_37_1:^  SpecCnt_37_2:^
SpecCnt_38_1:^  SpecCnt_38_2:^
SpecCnt_39_1:^  SpecCnt_39_2:^
SpecCnt_40_1:^  SpecCnt_40_2:^
SpecCnt_41_1:^  SpecCnt_41_2:^
SpecCnt_42_1:^  SpecCnt_42_2:^
SpecCnt_43_1:^  SpecCnt_43_2:^
SpecCnt_44_1:^  SpecCnt_44_2:^
SpecCnt_45_1:^  SpecCnt_45_2:^
SpecCnt_46_1:^  SpecCnt_46_2:^
SpecCnt_47_1:^  SpecCnt_47_2:^
SpecCnt_48_1:^  SpecCnt_48_2:^
SpecCnt_49_1:^  SpecCnt_49_2:^
SpecCnt_50_1:^  SpecCnt_50_2:^
SpecCnt_51_1:^  SpecCnt_51_2:^
SpecCnt_52_1:^  SpecCnt_52_2:^
SpecCnt_53_1:^  SpecCnt_53_2:^
SpecCnt_54_1:^  SpecCnt_54_2:^
SpecCnt_55_1:^  SpecCnt_55_2:^
SpecCnt_56_1:^  SpecCnt_56_2:^
SpecCnt_57_1:^  SpecCnt_57_2:^
SpecCnt_58_1:^  SpecCnt_58_2:^
CandidateOfScience:^
CandidateOfScience_w:^
DoctorofScience   :^
DoctorofScience_w   :^
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
HighKval_3                     ^
HighKval_4                     ^
HighKval_5                     ^
HighKval_6                     ^
HighKval_7                     ^
HighKval_8                     ^

Stager_3                       ^
Stager_4                       ^
Stager_5                       ^
Stager_6                       ^
Stager_7                       ^
Stager_8                       ^

LernInFirst_3                  ^
LernInFirst_4                  ^
LernInFirst_5                  ^
LernInFirst_6                  ^
LernInFirst_7                  ^
LernInFirst_8                  ^

SmegProf_3                      ^
SmegProf_4                      ^
SmegProf_5                      ^
SmegProf_6                      ^
SmegProf_7                      ^
SmegProf_8                      ^

Perepodgotov_3                   ^
Perepodgotov_4                   ^
Perepodgotov_5                   ^
Perepodgotov_6                   ^
Perepodgotov_7                   ^
Perepodgotov_8                   ^

OutThereHighKval_3               ^
OutThereHighKval_4               ^
OutThereHighKval_5               ^
OutThereHighKval_6               ^
OutThereHighKval_7               ^
OutThereHighKval_8               ^

OutThereStager_3                  ^
OutThereStager_4                  ^
OutThereStager_5                  ^
OutThereStager_6                  ^
OutThereStager_7                  ^
OutThereStager_8                  ^

OutProf_3                         ^
OutProf_4                         ^
OutProf_5                         ^
OutProf_6                         ^
OutProf_7                         ^
OutProf_8                         ^
!--------------------------
BossFio: ^
FIO_isp: ^
isp_posittion: ^
isp_fone: ^
FormDate: ^
.endform