/*
  ษอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
  บ       ’   "T O P   S O F T"                                       บ
  บ      เฎฅชโ "€"                                                 บ
  บ      ฅเแจ๏ : 5.8                                                   บ
  บ       งเ กฎโ ซ:  ฎๅฎข  ..                                       บ
  บ       งญ ็ฅญจฅ:  ”ฎเฌ  ’-8a  ‘ขฎคญ๋ฉ ฏเจช ง ฎก ใขฎซ์ญฅญจจ          บ
  บ       เ ฌฅโเ๋:                                                     บ
  บ      งฌฅญฅญจ๏: ฌ ฉ 2001 - ญฎข ๏ ไฎเฌ !!!                           บ
  ศอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
*/
#doc
”ฎเฌ  ’-8a  ‘ขฎคญ๋ฉ ฏเจช ง ฎก ใขฎซ์ญฅญจจ
#end
.form Nfrmt8A_2004
.Hide
.Fields
เฃ ญจง ๆจ๏  
TitleDocNrec : comp
ญฎฌฅเ_คฎชใฌฅญโ   ค โ _แฎแโ ขซฅญจ๏
ContDocNrec : comp
PersNrec : comp
AppointNrec : comp
FIO
FIO_VP
TabN
ฏฎคเ งคฅซฅญจฅ
คฎซฆญฎแโ์
ContractNmb
ContractDate
DisDate
Reason1
Reason2
Reason3
Reason
ReasonDelDop
ProfNmb
ฎซฆญใช
”จฎใช

dProf
nProf

.EndFields

^ ^ ^ ^ ^
.{ myPsnCycle8A_2004 CheckEnter
^ ^ ^ ^ ^ ^ ^ ^
^ ^ ^ ^ ^ ^ ^ ^ ^
.}
^ ^
^ ^
.endform
