/*
  ษอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
  บ       ’   "T O P   S O F T",  €    "       € ’  €  ’"     บ
  บ      เฎฅชโ    : €€’€  (แ) 2000                                บ
  บ      ‘จแโฅฌ    : “ฏเ ขซฅญจฅ ฏฅเแฎญ ซฎฌ                              บ
  บ      ฅเแจ๏    : 5.8                                                บ
  บ       งเ กฎโ ซ: €ญโฎญฎขจ็ €..     13/06/2001                      บ
  บ       งญ ็ฅญจฅ: โ โญฎฅ เ แฏจแ ญจฅ ฏฎ ไฎเฌฅ ’-3 ฏเจช ง ü 136       บ
  บ      งฌฅญฅญจ๏ :                                                    บ
  ศอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
*/

#doc
โ โญฎฅ เ แฏจแ ญจฅ ฏฎ ไฎเฌฅ ’-3 ฏเจช ง ü 136
#end
.form t_3_2004
.Hide
.Fields
KatOrg_Name
KatOrg_Okpo

stBeg1
stBeg2
stBeg3
stBeg4
stBeg5
stBeg6
stBeg7
stBeg8
stBeg9
stBeg10
stBeg12
stBeg11

stTitul1
stTitul2
stTitul3

cStaffStruct
nRecKPS
KPSName
KPSCode
staff1
staff2
staff3
staff4
staff11
staff5

topKoef

staff6
staff7
staff8
staff9
staff10
staff12

stEnd1
stEnd11
stEnd_col_5
stEnd2
stEnd3
stEnd4
stEnd5


.endFields

KatOrg_Name               ^
KatOrg_Okpo               ^

stBeg1                    ^
stBeg2                    ^
stBeg3                    ^
stBeg4                    ^
stBeg5                    ^
stBeg6                    ^
stBeg7                    ^
stBeg8                    ^
stBeg9                    ^
stBeg10                   ^
stBeg12                   ^
stBeg11                   ^

stTitul1                  ^
stTitul2                  ^
stTitul3                  ^

.{t3_2004_Cycle1  CheckEnter
cStaffStruct              ^
nRecKPS                   ^
KPSName                   ^
KPSCode                   ^
staff1                    ^
staff2                    ^
staff3                    ^
staff4                    ^
staff11                   ^
staff5                    ^

topKoef                   ^

staff6                    ^
staff7                    ^
staff8                    ^
staff9                    ^
staff10                   ^
.{t3_2004_Cycle2  CheckEnter
staff12                   ^
.}
.}

stEnd1                    ^
stEnd11                   ^
stEnd_col_5               ^
stEnd2                    ^
stEnd3                    ^
stEnd4                    ^
stEnd5                    ^

.endform
