#doc
#Doc_APlan
„¨ £à ¬¬  ƒ ­ââ  å®§ï©áâ¢¥­­®£® ¯« ­ 
#end
.form ganta_kip
.Fields
  s_prgcode s_nameap s_datab s_datee s_executor
  prgcode nameap datab datee executor
  periodname periodbeg periodend
  s_gantaline
  gantaline
.EndFields
ÿ                             „ˆ€ƒ€ŒŒ€ ƒ€’’€ •Ž‡Ÿ‰‘’‚…ŽƒŽ ‹€€ÿ
ÿÚÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂ
³ ã­ªâ      ³  ¨¬¥­®¢ ­¨¥                                                       ³   ç «®  ³ Žª®­ç ­¨¥ ³ Žâ¢¥âáâ¢¥­­ë©         ³
ÃÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅ
³            ³                                                                    ³          ³           ³                       ³ÿ
.{ganta_kip_Cycle1
.if ganta_kip_if9
ÿ‘³            ³                                                                    ³          ³           ³                       ³
³@@@@@@@@@@@@³ @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@³@@@@@@@@@@³@@@@@@@@@@@³@@@@@@@@@@@@@@@@@@@@@@ ³ÿ‘
.else
ÿ³@@@@@@@@@@@@³ @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@³@@@@@@@@@@³@@@@@@@@@@@³@@@@@@@@@@@@@@@@@@@@@@ ³ÿ
.end
.}

.{ganta_kip_Cycle2

ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
            ÿ"^"ÿ cÿ… ^ ÿ…¯® ÿ… ^ÿ…
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

.{ganta_kip_Cycle3
.if ganta_kip_if10

ÿ^ÿ
.else
^
.end
.}

.}
.endform
