/*
 ษอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
 บ                     (c) 1994,97 ชฎเฏฎเ ๆจ๏ €€’€                      บ
 บ เฎฅชโ        : €€’€                                                 บ
 บ ‘จแโฅฌ        : “ฏเ ขซฅญจฅ ฏเฎค ฆ ฌจ                                      บ
 บ ฅเแจ๏        : 5.00                                                      บ
 บ  งญ ็ฅญจฅ    :  ๆฅญชจ-โ็ฅโ                                             บ
 บ โขฅโแโขฅญญ๋ฉ : ใเกฅญชฎ เจฉ ข ญฎขจ็ (YURI)                             บ
 ศอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
*/
#doc
 ๆฅญชจ-โ็ฅโ
#end
.set name = 'KatNacen'
.NameInList ' งฎข ๏ ไฎเฌ '
.hide
.fields
 field1
 field2
 field3
 field4
 field5
.endfields

   ^
.{

   ^
   ^
   ^
   ^
.}
.endform

#doc
‘ฏจแฎช ญ ๆฅญฎช
#end
.linkform 'KatNacen_01' prototype is KatNacen
.NameInList '‘ฏจแฎช ญ ๆฅญฎช'
.fields
 CommonFormHeader
 field1
 field2
 field3
 field4
 field5
.endfields
  ^

   ^
.{

   ^
   ^
   ^
   ^
.}
.endform
