/*
 ษอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
 บ                     (c) 1994,00 ชฎเฏฎเ ๆจ๏ €€’€                      บ
 บ เฎฅชโ        : €€’€                                                 บ
 บ ‘จแโฅฌ        : €ขโฎโเ ญแฏฎเโ                                             บ
 บ ฅเแจ๏        : 6.00                                                      บ
 บ  งญ ็ฅญจฅ    : เฎกฅฃจ ่จญ                                               บ
 บ โขฅโแโขฅญญ๋ฉ : ซ cจช  ขฅซ ซ คจฌจเฎขจ็                                 บ
 ศอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
*/
.set name='Shin_Rep'
.hide
.fields
  Filter

  NaimPred BegDate  EndDate
  AnalGroup

  DatePL NPL
  NomShin ShinPos
   ProbegAll 

  AnalItg
   ProbegAllItg 
.endfields


.{
^
.}
^ ^ ^
.{ CheckEnter GroupAnalShina
^

.{ CheckEnter DocAnalShina
^ ^ ^ ^ ^ 
.}
.{ CheckEnter TotalAnalShina
^
^ 
.}
.}
.endform
