/*
   =====================================================================
  │      Н Т О  "T O P   S O F T",  А О   "Н О В Ы Й   А Т Л А Н Т"     │
  │      Проект    : ГАЛАКТИКА  (с) 2000                                │
  │      Система   : Управление персоналом                              │
  │      Версия    : 5.8                                                │
  │      Разработал: Антонович А.К.     03/08/2001                      │
  │      Назначение:                                                    │
  │      Изменения :                                                    │
   =====================================================================
*/
#doc
  Форма для отчета ГАЗ-30
#end
.form GAZ_30
.Hide

.Fields

OrgName
period
DateBeg
DateEnd

Count_1
Count_2
Count_3
Count_4
Count_5
Count_6
Count_7
Count_8
Count_9
Count_10
Count_11
Count_12
Count_13
Count_14
Count_15
Count_16
Count_17

BossFIO
ExecutFIO
CurDate

.endFields

OrgName               ^

period                ^
DateBeg               ^
DateEnd               ^

Count_1               ^
Count_2               ^
Count_3               ^
Count_4               ^
Count_5               ^
Count_6               ^
Count_7               ^
Count_8               ^
Count_9               ^
Count_10              ^
Count_11              ^
Count_12              ^
Count_13              ^
Count_14              ^
Count_15              ^
Count_16              ^
Count_17              ^

BossFIO               ^
ExecutFIO             ^
CurDate               ^

.endform