/*
  ษอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
  บ       ’   "T O P   S O F T",  €    "       € ’  €  ’"     บ
  บ      เฎฅชโ    : €€’€  (แ) 2000                                บ
  บ      ‘จแโฅฌ    : “ฏเ ขซฅญจฅ ฏฅเแฎญ ซฎฌ                              บ
  บ      ฅเแจ๏    : 5.8                                                บ
  บ       งเ กฎโ ซ: €ญโฎญฎขจ็ €..     13/06/2001                      บ
  บ       งญ ็ฅญจฅ: “็ฅโญ ๏ ช เโฎ็ช  คฎชโฎเ  จ ช ญคจค โ  ญ ใช (“ชเ จญ )บ
  บ      งฌฅญฅญจ๏ :                                                    บ
  ศอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
*/

#doc
“็ฅโญ ๏ ช เโฎ็ช  คฎชโฎเ  จ ช ญคจค โ  ญ ใช (“ชเ จญ )
#end
.form t_4_Ukr
.Hide
.Fields

PersonsNRec

Komy_podaetsja
Ministerstvo
Koncern
KatOrg_Name
Adres_KatOrg
Form_Sobstv
Form_Upravl
Vid_Func
Num_doc

Num_dipl
Ser_dipl

date_Na

FIO
Sex
Date_Born       : Date
Date_Candidat
Date_Doctor
Date_Diplom
Obl_Nauki_Dis
Spec_Dis
Tema_Doctor1
Tema_Doctor2
Izbr1
Academ1
Date_Select1
Izbr2
Academ2
Date_Select2
Educ_Zvan
Date_Educ_Zvan
Post
Spec

Lang1
Lang2
Lang3
Lang4
Lang5
Lang6
Lang7
Lang8
Lang9

Date_Sostavl    : Date

BossName
IspName

.endFields

PersonsNRec            ^

Komy_podaetsja         ^
Ministerstvo           ^
Koncern                ^
KatOrg_Name            ^
Adres_KatOrg           ^
Form_Sobstv            ^
Form_Upravl            ^
Vid_Func               ^
Num_doc                ^

Num_dipl               ^
Ser_dipl               ^

date_Na                ^

FIO                    ^
Sex                    ^
Date_Born              ^
Date_Candidat          ^
Date_Doctor            ^
Date_Diplom            ^
Obl_Nauki_Dis          ^
Spec_Dis               ^
Tema_Doctor1           ^
Tema_Doctor2           ^
Izbr1                  ^
Academ1                ^
Date_Select1           ^
Izbr1                  ^
Academ2                ^
Date_Select2           ^
Educ_Zvan              ^
Date_Educ_Zvan         ^
Post                   ^
Spec                   ^

Lang1                  ^
Lang2                  ^
Lang3                  ^
Lang4                  ^
Lang5                  ^
Lang6                  ^
Lang7                  ^
Lang8                  ^
Lang9                  ^

Date_Sostavl           ^

BossName               ^
IspName                ^

.endform