/*
  ษอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
  บ       ’   "T O P   S O F T",  €    "       € ’  €  ’"     บ
  บ      เฎฅชโ    : €€’€  (แ) 2000                                บ
  บ      ‘จแโฅฌ    : “ฏเ ขซฅญจฅ ฏฅเแฎญ ซฎฌ                              บ
  บ      ฅเแจ๏    : 5.8                                                บ
  บ       งเ กฎโ ซ: €ญโฎญฎขจ็ €..     24/01/2002                      บ
  บ       งญ ็ฅญจฅ: ’เใคฎขฎฉ คฎฃฎขฎเ คซ๏ ฅซ เใแจ                      บ
  บ      งฌฅญฅญจ๏ :                                                    บ
  ศอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
*/

#doc
’เใคฎขฎฉ คฎฃฎขฎเ คซ๏ ฅซ เใแจ
#end
.form td_Bel
.Hide
.Fields

KatOrg_Name
KatOrg_OKPO
Num_Doc
Date_Doc
BossFIO
FIO
FIO_VP
AppPostCat_Name
KlKatego_NaiKat
Razrad
AppKatPodr_Name

TestPeriodDn
TestPeriodMes

AppointDate
DateEnd

KlSovm_NSovm

Name1
dat1

topKoef

Name1_1
dat1_1

Name2_1
dat2_1

dat3

.endFields

KatOrg_Name              ^
KatOrg_OKPO              ^
Num_Doc                  ^
Date_Doc                 ^
FIO                      ^
FIO_VP                   ^
BossFIO                  ^
AppPostCat_Name          ^
KlKatego_NaiKat          ^
Razrad                   ^
AppKatPodr_Name          ^

TestPeriodDn             ^
TestPeriodMes            ^

AppointDate              ^
DateEnd                  ^

KlSovm_NSovm             ^

Name1                    ^
dat1                     ^

topKoef                  ^

Name1_1                  ^
dat1_1                   ^

Name2_1                  ^
dat2_1                   ^

dat3                     ^
.endform