/*
  ÉÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ»
  º       ’   "T O P   S O F T",  €    "  ‚ › ‰   € ’ ‹ €  ’"     º
  º      à®¥ªâ    : ƒ€‹€Š’ˆŠ€  (á) 2000                                º
  º      ‘¨áâ¥¬    : “¯à ¢«¥­¨¥ ¯¥àá®­ «®¬                              º
  º      ‚¥àá¨ï    : 5.8, 7.1                                           º
  º       §à ¡®â «: €­â®­®¢¨ç €.Š.     09/10/2002                      º
  º       §­ ç¥­¨¥: âç¥â:  ¯à¨ç¨­ å § ¡®«¥¢ ¥¬®áâ¨                   º
  º      ˆ§¬¥­¥­¨ï :                                                    º
  ÈÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ¼
*/

#doc
âç¥â ® ¯à¨ç¨­ å § ¡®«¥¢ ¥¬®áâ¨
#end
.form F16VN
.hide
.fields
MonthBeg
MonthEnd
Year

OrgName
ParentOrgName
à£ ­“¯à
”®à¬ ‘®¡áâ¢
Adres

Š
Š‹
‘“
ŠX
Š„
‘€’
Š”‘
Š”


CountBL_1   CountKDay_1
CountBL_2   CountKDay_2
CountBL_3   CountKDay_3
CountBL_4   CountKDay_4
CountBL_5   CountKDay_5
CountBL_6   CountKDay_6
CountBL_7   CountKDay_7
CountBL_8   CountKDay_8
CountBL_9   CountKDay_9
CountBL_10  CountKDay_10
CountBL_11  CountKDay_11
CountBL_12  CountKDay_12
CountBL_13  CountKDay_13
CountBL_14  CountKDay_14
CountBL_15  CountKDay_15
CountBL_16  CountKDay_16
CountBL_17  CountKDay_17
CountBL_18  CountKDay_18
CountBL_19  CountKDay_19
CountBL_20  CountKDay_20
CountBL_21  CountKDay_21
CountBL_22  CountKDay_22
CountBL_23  CountKDay_23
CountBL_24  CountKDay_24
CountBL_25  CountKDay_25
CountBL_26  CountKDay_26
CountBL_27  CountKDay_27
CountBL_28  CountKDay_28
CountBL_29  CountKDay_29
CountBL_30  CountKDay_30
CountBL_31  CountKDay_31
CountBL_32  CountKDay_32
CountBL_33  CountKDay_33
CountBL_34  CountKDay_34
CountBL_35  CountKDay_35
CountBL_36  CountKDay_36
CountBL_37  CountKDay_37
CountBL_38  CountKDay_38
CountBL_39  CountKDay_39
CountBL_40  CountKDay_40
CountBL_41  CountKDay_41
CountBL_42  CountKDay_42
CountBL_43  CountKDay_43
CountBL_44  CountKDay_44
CountBL_45  CountKDay_45
CountBL_46  CountKDay_46
CountBL_47  CountKDay_47
CountBL_48  CountKDay_48
CountBL_49  CountKDay_49
CountBL_50  CountKDay_50
CountBL_51  CountKDay_51
CountBL_52  CountKDay_52
CountBL_53  CountKDay_53
CountBL_54  CountKDay_54
CountBL_55  CountKDay_55
CountBL_56  CountKDay_56
CountBL_57  CountKDay_57
CountBL_58  CountKDay_58
CountBL_59  CountKDay_59
CountBL_60  CountKDay_60
CountBL_61  CountKDay_61
CountBL_62  CountKDay_62
CountBL_63  CountKDay_63
CountBL_64  CountKDay_64
CountBL_65  CountKDay_65
CountBL_66  CountKDay_66
CountBL_67  CountKDay_67
CountBL_68  CountKDay_68
CountBL_69  CountKDay_69
CountBL_70  CountKDay_70
CountBL_71  CountKDay_71
CountBL_72
CountBL_73

AppBoss FioBoss

.endfields

MonthBeg                     ^
MonthEnd                     ^
Year                         ^

OrgName                      ^
ParentOrgName                ^
à£ ­“¯à                     ^
”®à¬ ‘®¡áâ¢                  ^
Adres                        ^

Š                         ^
Š‹                        ^
‘“                         ^
ŠX                        ^
Š„                         ^
‘€’                        ^
Š”‘                         ^
Š”                        ^

CountBL_1   CountKDay_1      ^ ^
CountBL_2   CountKDay_2      ^ ^
CountBL_3   CountKDay_3      ^ ^
CountBL_4   CountKDay_4      ^ ^
CountBL_5   CountKDay_5      ^ ^
CountBL_6   CountKDay_6      ^ ^
CountBL_7   CountKDay_7      ^ ^
CountBL_8   CountKDay_8      ^ ^
CountBL_9   CountKDay_9      ^ ^
CountBL_10  CountKDay_10     ^ ^
CountBL_11  CountKDay_11     ^ ^
CountBL_12  CountKDay_12     ^ ^
CountBL_13  CountKDay_13     ^ ^
CountBL_14  CountKDay_14     ^ ^
CountBL_15  CountKDay_15     ^ ^
CountBL_16  CountKDay_16     ^ ^
CountBL_17  CountKDay_17     ^ ^
CountBL_18  CountKDay_18     ^ ^
CountBL_19  CountKDay_19     ^ ^
CountBL_20  CountKDay_20     ^ ^
CountBL_21  CountKDay_21     ^ ^
CountBL_22  CountKDay_22     ^ ^
CountBL_23  CountKDay_23     ^ ^
CountBL_24  CountKDay_24     ^ ^
CountBL_25  CountKDay_25     ^ ^
CountBL_26  CountKDay_26     ^ ^
CountBL_27  CountKDay_27     ^ ^
CountBL_28  CountKDay_28     ^ ^
CountBL_29  CountKDay_29     ^ ^
CountBL_30  CountKDay_30     ^ ^
CountBL_31  CountKDay_31     ^ ^
CountBL_32  CountKDay_32     ^ ^
CountBL_33  CountKDay_33     ^ ^
CountBL_34  CountKDay_34     ^ ^
CountBL_35  CountKDay_35     ^ ^
CountBL_36  CountKDay_36     ^ ^
CountBL_37  CountKDay_37     ^ ^
CountBL_38  CountKDay_38     ^ ^
CountBL_39  CountKDay_39     ^ ^
CountBL_40  CountKDay_40     ^ ^
CountBL_41  CountKDay_41     ^ ^
CountBL_42  CountKDay_42     ^ ^
CountBL_43  CountKDay_43     ^ ^
CountBL_44  CountKDay_44     ^ ^
CountBL_45  CountKDay_45     ^ ^
CountBL_46  CountKDay_46     ^ ^
CountBL_47  CountKDay_47     ^ ^
CountBL_48  CountKDay_48     ^ ^
CountBL_49  CountKDay_49     ^ ^
CountBL_50  CountKDay_50     ^ ^
CountBL_51  CountKDay_51     ^ ^
CountBL_52  CountKDay_52     ^ ^
CountBL_53  CountKDay_53     ^ ^
CountBL_54  CountKDay_54     ^ ^
CountBL_55  CountKDay_55     ^ ^
CountBL_56  CountKDay_56     ^ ^
CountBL_57  CountKDay_57     ^ ^
CountBL_58  CountKDay_58     ^ ^
CountBL_59  CountKDay_59     ^ ^
CountBL_60  CountKDay_60     ^ ^
CountBL_61  CountKDay_61     ^ ^
CountBL_62  CountKDay_62     ^ ^
CountBL_63  CountKDay_63     ^ ^
CountBL_64  CountKDay_64     ^ ^
CountBL_65  CountKDay_65     ^ ^
CountBL_66  CountKDay_66     ^ ^
CountBL_67  CountKDay_67     ^ ^
CountBL_68  CountKDay_68     ^ ^
CountBL_69  CountKDay_69     ^ ^
CountBL_70  CountKDay_70     ^ ^
CountBL_71  CountKDay_71     ^ ^
CountBL_72                   ^
CountBL_73                   ^

AppBoss FioBoss              ^ ^
.endform