/*
  ษอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
  บ       ’   "T O P   S O F T",  €    "       € ’  €  ’"     บ
  บ      เฎฅชโ    : €€’€  (แ) 2000                                บ
  บ      ‘จแโฅฌ    : “ฏเ ขซฅญจฅ ฏฅเแฎญ ซฎฌ                              บ
  บ      ฅเแจ๏    : 5.8, 7.1                                           บ
  บ       งเ กฎโ ซ: €ญโฎญฎขจ็ €..     19/04/2002                      บ
  บ       งญ ็ฅญจฅ: โ็ฅโ: เฎขฅคฅญจฅ ฏเฎไฎแฌฎโเ                       บ
  บ      งฌฅญฅญจ๏ :                                                    บ
  ศอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
*/

#doc
โ็ฅโ: เฎขฅคฅญจฅ ฏเฎไฎแฌฎโเ 
#end
.form ProfInspect
.hide
.fields
OrgName

DatePeriod
DateBegPeriod : date
DateEndPeriod : date

!.{ ProfInspect1  CheckEnter
NumPP
KodPlace
TabNum
FIO
BornYear
Post
Staj
CodeFaktor
IsDoctor
Labor
OldDate
NewDate
!.}

ฎซฆญใช
”จฎใช


.endfields

OrgName                      ^

DatePeriod                   ^
DateBegPeriod : date         ^
DateEndPeriod : date         ^

.{ ProfInspect1  CheckEnter
NumPP                        ^
KodPlace                     ^
TabNum                       ^
FIO                          ^
BornYear                     ^
Post                         ^
Staj                         ^
CodeFaktor                   ^
IsDoctor                     ^
Labor                        ^
OldDate                      ^
NewDate                      ^
.}

ฎซฆญใช                     ^
”จฎใช                       ^

.endform
