LogStrToFile(FBasName, 'Sub CreateReportHeaders()');
LogStrToFile(FBasName, '''');
LogStrToFile(FBasName, ''' Создание и форматирование общего заголовка всех отчетов');
LogStrToFile(FBasName, '''');
LogStrToFile(FBasName, '''');
LogStrToFile(FBasName, '');
LogStrToFile(FBasName, '    Dim SheetNames(6), SheetHeaders(6), RightChars(6) As String');
LogStrToFile(FBasName, '    Dim ExtColumn(6) As Byte');
LogStrToFile(FBasName, '    ExtColumn(1) = 4');
LogStrToFile(FBasName, '    ExtColumn(2) = 9');
LogStrToFile(FBasName, '    ExtColumn(3) = 12');
LogStrToFile(FBasName, '    ExtColumn(4) = 13');
LogStrToFile(FBasName, '    ExtColumn(5) = 9');
LogStrToFile(FBasName, '    ExtColumn(6) = 14');
LogStrToFile(FBasName, '    ');
LogStrToFile(FBasName, '    RightChars(1) = "R"');
LogStrToFile(FBasName, '    RightChars(2) = "W"');
LogStrToFile(FBasName, '    RightChars(3) = "Z"');
LogStrToFile(FBasName, '    RightChars(4) = "AA"');
LogStrToFile(FBasName, '    RightChars(5) = "W"');
LogStrToFile(FBasName, '    RightChars(6) = "AB"');
LogStrToFile(FBasName, '    ');
LogStrToFile(FBasName, '    SheetNames(1) = "Статусы"');
LogStrToFile(FBasName, '    SheetNames(2) = "Договор со спецификацией"');
LogStrToFile(FBasName, '    SheetNames(3) = "Договор с КП"');
LogStrToFile(FBasName, '    SheetNames(4) = "Наряд-заказы"');
LogStrToFile(FBasName, '    SheetNames(5) = "Платежи"');
LogStrToFile(FBasName, '    SheetNames(6) = "Отгрузки"');
LogStrToFile(FBasName, '    ');
LogStrToFile(FBasName, '    SheetHeaders(1) = "Отчет о ходе визирования и об изменении условий договора"');
LogStrToFile(FBasName, '    SheetHeaders(2) = "Договор со спецификацией"');
LogStrToFile(FBasName, '    SheetHeaders(3) = "Договор с календарным планом"');
LogStrToFile(FBasName, '    SheetHeaders(4) = "Сформированные по договору наряд-заказы"');
LogStrToFile(FBasName, '    SheetHeaders(5) = "Платежно-расчетные документы по договору"');
LogStrToFile(FBasName, '    SheetHeaders(6) = "Сформированные по договору товарно-сопроводительные документы"');
LogStrToFile(FBasName, '    ');
LogStrToFile(FBasName, '    Dim NewSheet As Variant');
LogStrToFile(FBasName, '    NewSheet = Null');
LogStrToFile(FBasName, '    For i = 1 To 6');
LogStrToFile(FBasName, '        If i = 1 Then');
LogStrToFile(FBasName, '            Set NewSheet = Sheets.Add');
LogStrToFile(FBasName, '        Else');
LogStrToFile(FBasName, '            Set NewSheet = Sheets.Add(after:=NewSheet)');
LogStrToFile(FBasName, '        End If');
LogStrToFile(FBasName, '        NewSheet.Select');
LogStrToFile(FBasName, '        ActiveSheet.Name = SheetNames(i)');
LogStrToFile(FBasName, '        With NewSheet.PageSetup');
LogStrToFile(FBasName, '            .Orientation = xlLandscape');
LogStrToFile(FBasName, '            .Zoom = False');
LogStrToFile(FBasName, '            .FitToPagesWide = 1');
LogStrToFile(FBasName, '            .FitToPagesTall = 1000');
LogStrToFile(FBasName, '        End With');
LogStrToFile(FBasName, '        With NewSheet');
LogStrToFile(FBasName, '            Range("F:G").NumberFormat = "dd\/mm\/yyyy"');
LogStrToFile(FBasName, '            Range("L:L").NumberFormat = "#,##0.00"');
LogStrToFile(FBasName, '            Range("F:H,J:K").HorizontalAlignment = xlCenter');
LogStrToFile(FBasName, '            Select Case i');
LogStrToFile(FBasName, '                Case 1');
LogStrToFile(FBasName, '                    Range("O:O").HorizontalAlignment = xlCenter');
LogStrToFile(FBasName, '                Case 2');
LogStrToFile(FBasName, '                    Range("O:P,T:T").HorizontalAlignment = xlCenter');
LogStrToFile(FBasName, '                    Range("O:O").NumberFormat = "@"');
LogStrToFile(FBasName, '                    Range("S:S").NumberFormat = "0.00"');
LogStrToFile(FBasName, '                    Range("U:V").NumberFormat = "#,##0.00"');
LogStrToFile(FBasName, '                Case 3');
LogStrToFile(FBasName, '                    Range("O:P,S:T,X:X").HorizontalAlignment = xlCenter');
LogStrToFile(FBasName, '                    Range("O:O,S:S").NumberFormat = "@"');
LogStrToFile(FBasName, '                    Range("Q:Q,Y:Y,Z:Z").NumberFormat = "#,##0.00"');
LogStrToFile(FBasName, '                    Range("W:W").NumberFormat = "0.00"');
LogStrToFile(FBasName, '                Case 4');
LogStrToFile(FBasName, '                    Range("O:Q,X:X,AA:AA").HorizontalAlignment = xlCenter');
LogStrToFile(FBasName, '                    Range("P:P,T:T").NumberFormat = "@"');
LogStrToFile(FBasName, '                    Range("Q:Q").NumberFormat = "dd\/mm\/yyyy"');
LogStrToFile(FBasName, '                    Range("W:W").NumberFormat = "0.00"');
LogStrToFile(FBasName, '                    Range("Y:Y,Z:Z").NumberFormat = "#,##0.00"');
LogStrToFile(FBasName, '                Case 5');
LogStrToFile(FBasName, '                    Range("O:Q,W:W").HorizontalAlignment = xlCenter');
LogStrToFile(FBasName, '                    Range("P:P,T:T").NumberFormat = "@"');
LogStrToFile(FBasName, '                    Range("Q:Q").NumberFormat = "dd\/mm\/yyyy"');
LogStrToFile(FBasName, '                    Range("V:V").NumberFormat = "#,##0.00"');
LogStrToFile(FBasName, '                Case 6');
LogStrToFile(FBasName, '                    Range("O:Q,V:V,Y:Y,AC:AB").HorizontalAlignment = xlCenter');
LogStrToFile(FBasName, '                    Range("P:P,R:R,S:S,V:V").NumberFormat = "@"');
LogStrToFile(FBasName, '                    Range("Q:Q").NumberFormat = "dd\/mm\/yyyy"');
LogStrToFile(FBasName, '                    Range("X:X").NumberFormat = "0.00"');
LogStrToFile(FBasName, '                    Range("Z:Z,AA:AA").NumberFormat = "#,##0.00"');
LogStrToFile(FBasName, '            End Select');
LogStrToFile(FBasName, '            Rows("1:3").NumberFormat = "General"');
LogStrToFile(FBasName, '            Range("A1").FormulaR1C1 = SheetHeaders(i)');
LogStrToFile(FBasName, '            Range("A1:" + RightChars(i) + "1").Merge');
LogStrToFile(FBasName, '            Range("A2").FormulaR1C1 = "Номер и дата договора"');
LogStrToFile(FBasName, '            Range("A2:A3").Merge');
LogStrToFile(FBasName, '            Range("B2").FormulaR1C1 = "Контрагент договора"');
LogStrToFile(FBasName, '            Range("B2:B3").Merge');
LogStrToFile(FBasName, '            Range("C2").FormulaR1C1 = "Номер и дата соглашения"');
LogStrToFile(FBasName, '            Range("C2:C3").Merge');
LogStrToFile(FBasName, '            Range("D2").FormulaR1C1 = "Контрагент соглашения"');
LogStrToFile(FBasName, '            Range("D2:D3").Merge');
LogStrToFile(FBasName, '            Range("E2").FormulaR1C1 = "Ссылка на вышестоящее соглашение"');
LogStrToFile(FBasName, '            Range("E2:E3").Merge');
LogStrToFile(FBasName, '            Range("F2").FormulaR1C1 = "Срок действия"');
LogStrToFile(FBasName, '            Range("F2:G2").Merge');
LogStrToFile(FBasName, '            Range("F3").FormulaR1C1 = "С"');
LogStrToFile(FBasName, '            Range("G3").FormulaR1C1 = "По"');
LogStrToFile(FBasName, '            Range("H2").FormulaR1C1 = "Вид"');
LogStrToFile(FBasName, '            Range("H2:H3").Merge');
LogStrToFile(FBasName, '            Range("I2").FormulaR1C1 = "Назначение"');
LogStrToFile(FBasName, '            Range("I2:I3").Merge');
LogStrToFile(FBasName, '            Range("J2").FormulaR1C1 = "Тип по валюте"');
LogStrToFile(FBasName, '            Range("J2:J3").Merge');
LogStrToFile(FBasName, '            Range("K2").FormulaR1C1 = "Валюта документа"');
LogStrToFile(FBasName, '            Range("K2:K3").Merge');
LogStrToFile(FBasName, '            Range("L2").FormulaR1C1 = "Сумма"');
LogStrToFile(FBasName, '            Range("L2:L3").Merge');
LogStrToFile(FBasName, '            Range("M2").FormulaR1C1 = "Ответственные по договору"');
LogStrToFile(FBasName, '            Range("M2:N2").Merge');
LogStrToFile(FBasName, '            Range("M3").FormulaR1C1 = "Подразделение"');
LogStrToFile(FBasName, '            Range("N3").FormulaR1C1 = "Сотрудник"');
LogStrToFile(FBasName, '            Select Case i');
LogStrToFile(FBasName, '                Case 1');
LogStrToFile(FBasName, '                    Range("O2").FormulaR1C1 = "Изменение статуса"');
LogStrToFile(FBasName, '                    Range("O2:" + RightChars(i) + "2").Merge');
LogStrToFile(FBasName, '                    Range("O3").FormulaR1C1 = "Дата и время"');
LogStrToFile(FBasName, '                    Range("P3").FormulaR1C1 = "До изменения"');
LogStrToFile(FBasName, '                    Range("Q3").FormulaR1C1 = "После изменения"');
LogStrToFile(FBasName, '                    Range("R3").FormulaR1C1 = "Комментарий"');
LogStrToFile(FBasName, '                Case 2');
LogStrToFile(FBasName, '                    Range("O2").FormulaR1C1 = "Спецификация"');
LogStrToFile(FBasName, '                    Range("O2:" + RightChars(i) + "2").Merge');
LogStrToFile(FBasName, '                    Range("O3").FormulaR1C1 = "№ п/п"');
LogStrToFile(FBasName, '                    Range("P3").FormulaR1C1 = "Направление"');
LogStrToFile(FBasName, '                    Range("Q3").FormulaR1C1 = "Группа"');
LogStrToFile(FBasName, '                    Range("R3").FormulaR1C1 = "Наименование"');
LogStrToFile(FBasName, '                    Range("S3").FormulaR1C1 = "Кол-во"');
LogStrToFile(FBasName, '                    Range("T3").FormulaR1C1 = "Ед.изм."');
LogStrToFile(FBasName, '                    Range("U3").FormulaR1C1 = "Цена"');
LogStrToFile(FBasName, '                    Range("V3").FormulaR1C1 = "Сумма"');
LogStrToFile(FBasName, '                    Range("W3").FormulaR1C1 = "Ответственное подразделение"');
LogStrToFile(FBasName, '                Case 3');
LogStrToFile(FBasName, '                    Range("O2").FormulaR1C1 = "Календарный план"');
LogStrToFile(FBasName, '                    Range("O2:R2").Merge');
LogStrToFile(FBasName, '                    Range("O3").FormulaR1C1 = "№"');
LogStrToFile(FBasName, '                    Range("P3").FormulaR1C1 = "Тип"');
LogStrToFile(FBasName, '                    Range("Q3").FormulaR1C1 = "Сумма"');
LogStrToFile(FBasName, '                    Range("R3").FormulaR1C1 = "Ответственное подразделение"');
LogStrToFile(FBasName, '                    Range("S2").FormulaR1C1 = "Спецификация ПКП"');
LogStrToFile(FBasName, '                    Range("S2:Z2").Merge');
LogStrToFile(FBasName, '                    Range("S3").FormulaR1C1 = "№ п/п"');
LogStrToFile(FBasName, '                    Range("T3").FormulaR1C1 = "Направление"');
LogStrToFile(FBasName, '                    Range("U3").FormulaR1C1 = "Группа"');
LogStrToFile(FBasName, '                    Range("V3").FormulaR1C1 = "Наименование"');
LogStrToFile(FBasName, '                    Range("W3").FormulaR1C1 = "Кол-во"');
LogStrToFile(FBasName, '                    Range("X3").FormulaR1C1 = "Ед.изм."');
LogStrToFile(FBasName, '                    Range("Y3").FormulaR1C1 = "Цена"');
LogStrToFile(FBasName, '                    Range("Z3").FormulaR1C1 = "Сумма"');
LogStrToFile(FBasName, '                Case 4');
LogStrToFile(FBasName, '                    Range("O2").FormulaR1C1 = "Платежно-расчетный документ"');
LogStrToFile(FBasName, '                    Range("O2:S2").Merge');
LogStrToFile(FBasName, '                    Range("O3").FormulaR1C1 = "Тип"');
LogStrToFile(FBasName, '                    Range("P3").FormulaR1C1 = "№"');
LogStrToFile(FBasName, '                    Range("Q3").FormulaR1C1 = "Дата"');
LogStrToFile(FBasName, '                    Range("R3").FormulaR1C1 = "Подразделение"');
LogStrToFile(FBasName, '                    Range("S3").FormulaR1C1 = "Пункт погрузки"');
LogStrToFile(FBasName, '                    Range("T2").FormulaR1C1 = "Спецификация наряд-заказа"');
LogStrToFile(FBasName, '                    Range("T2:AA2").Merge');
LogStrToFile(FBasName, '                    Range("T3").FormulaR1C1 = "№ п/п"');
LogStrToFile(FBasName, '                    Range("U3").FormulaR1C1 = "Группа"');
LogStrToFile(FBasName, '                    Range("V3").FormulaR1C1 = "Наименование"');
LogStrToFile(FBasName, '                    Range("W3").FormulaR1C1 = "Кол-во"');
LogStrToFile(FBasName, '                    Range("X3").FormulaR1C1 = "Ед.изм."');
LogStrToFile(FBasName, '                    Range("Y3").FormulaR1C1 = "Цена"');
LogStrToFile(FBasName, '                    Range("Z3").FormulaR1C1 = "Сумма"');
LogStrToFile(FBasName, '                    Range("AA3").FormulaR1C1 = "Ресурс"');
LogStrToFile(FBasName, '                Case 5');
LogStrToFile(FBasName, '                    Range("O2").FormulaR1C1 = "Платежно-расчетный документ"');
LogStrToFile(FBasName, '                    Range("O2:" + RightChars(i) + "2").Merge');
LogStrToFile(FBasName, '                    Range("O3").FormulaR1C1 = "Тип"');
LogStrToFile(FBasName, '                    Range("P3").FormulaR1C1 = "№"');
LogStrToFile(FBasName, '                    Range("Q3").FormulaR1C1 = "Дата"');
LogStrToFile(FBasName, '                    Range("R3").FormulaR1C1 = "Плательщик"');
LogStrToFile(FBasName, '                    Range("S3").FormulaR1C1 = "Получатель"');
LogStrToFile(FBasName, '                    Range("T3").FormulaR1C1 = "Основание"');
LogStrToFile(FBasName, '                    Range("U3").FormulaR1C1 = "Назначение"');
LogStrToFile(FBasName, '                    Range("V3").FormulaR1C1 = "Сумма"');
LogStrToFile(FBasName, '                    Range("W3").FormulaR1C1 = "Валюта"');
LogStrToFile(FBasName, '                Case 6');
LogStrToFile(FBasName, '                    Range("O2").FormulaR1C1 = "Товарно-сопроводительный документ"');
LogStrToFile(FBasName, '                    Range("O2:U2").Merge');
LogStrToFile(FBasName, '                    Range("O3").FormulaR1C1 = "Тип"');
LogStrToFile(FBasName, '                    Range("P3").FormulaR1C1 = "№"');
LogStrToFile(FBasName, '                    Range("Q3").FormulaR1C1 = "Дата"');
LogStrToFile(FBasName, '                    Range("R3").FormulaR1C1 = "Основание"');
LogStrToFile(FBasName, '                    Range("S3").FormulaR1C1 = "Наряд-заказ"');
LogStrToFile(FBasName, '                    Range("T3").FormulaR1C1 = "Грузоотправитель"');
LogStrToFile(FBasName, '                    Range("U3").FormulaR1C1 = "Грузополучатель"');
LogStrToFile(FBasName, '                    Range("V2").FormulaR1C1 = "Спецификация документа"');
LogStrToFile(FBasName, '                    Range("V2:AB2").Merge');
LogStrToFile(FBasName, '                    Range("V3").FormulaR1C1 = "№ п/п"');
LogStrToFile(FBasName, '                    Range("W3").FormulaR1C1 = "Наименование"');
LogStrToFile(FBasName, '                    Range("X3").FormulaR1C1 = "Кол-во"');
LogStrToFile(FBasName, '                    Range("Y3").FormulaR1C1 = "Ед.изм."');
LogStrToFile(FBasName, '                    Range("Z3").FormulaR1C1 = "Цена"');
LogStrToFile(FBasName, '                    Range("AA3").FormulaR1C1 = "Сумма"');
LogStrToFile(FBasName, '                    Range("AB3").FormulaR1C1 = "Валюта"');
LogStrToFile(FBasName, '            End Select');
LogStrToFile(FBasName, '            Cells.Select');
LogStrToFile(FBasName, '            Selection.Font.Size = 8');
LogStrToFile(FBasName, '            Rows("1:1").Select');
LogStrToFile(FBasName, '            Selection.Font.Size = 14');
LogStrToFile(FBasName, '            Selection.Font.Bold = True');
LogStrToFile(FBasName, '            Rows("2:3").Select');
LogStrToFile(FBasName, '            Selection.Font.Size = 10');
LogStrToFile(FBasName, '            Selection.Font.Bold = True');
LogStrToFile(FBasName, '            Rows("1:3").Select');
LogStrToFile(FBasName, '            With Selection');
LogStrToFile(FBasName, '                .HorizontalAlignment = xlCenter');
LogStrToFile(FBasName, '                .VerticalAlignment = xlCenter');
LogStrToFile(FBasName, '                .WrapText = True');
LogStrToFile(FBasName, '            End With');
LogStrToFile(FBasName, '            Columns("O:" + RightChars(i)).ColumnWidth = 25');
LogStrToFile(FBasName, '            Columns("A:N").ColumnWidth = 25');
LogStrToFile(FBasName, '            Columns("J:K").ColumnWidth = 10');
LogStrToFile(FBasName, '            Columns("L:L").ColumnWidth = 15');
LogStrToFile(FBasName, '            Columns("F:H").ColumnWidth = 10');
LogStrToFile(FBasName, '            ');
LogStrToFile(FBasName, '            Select Case i');
LogStrToFile(FBasName, '                Case 1');
LogStrToFile(FBasName, '                    Columns("O:O").ColumnWidth = 15');
LogStrToFile(FBasName, '                    Columns("Q:Q").ColumnWidth = 20');
LogStrToFile(FBasName, '                Case 2');
LogStrToFile(FBasName, '                    Columns("O:O").ColumnWidth = 5');
LogStrToFile(FBasName, '                    Columns("Q:P").ColumnWidth = 15');
LogStrToFile(FBasName, '                    Columns("Q:R").ColumnWidth = 20');
LogStrToFile(FBasName, '                    Columns("S:S").ColumnWidth = 7');
LogStrToFile(FBasName, '                    Columns("T:T").ColumnWidth = 8');
LogStrToFile(FBasName, '                    Columns("U:V").ColumnWidth = 15');
LogStrToFile(FBasName, '                    Columns("W:W").ColumnWidth = 25');
LogStrToFile(FBasName, '                Case 3');
LogStrToFile(FBasName, '                    Columns("O:O").ColumnWidth = 5');
LogStrToFile(FBasName, '                    Columns("Q:Q").ColumnWidth = 15');
LogStrToFile(FBasName, '                    Columns("S:S").ColumnWidth = 5');
LogStrToFile(FBasName, '                    Columns("T:V").ColumnWidth = 15');
LogStrToFile(FBasName, '                    Columns("W:W").ColumnWidth = 7');
LogStrToFile(FBasName, '                    Columns("X:X").ColumnWidth = 8');
LogStrToFile(FBasName, '                    Columns("Y:Z").ColumnWidth = 15');
LogStrToFile(FBasName, '                Case 4');
LogStrToFile(FBasName, '                    Columns("O:Q").ColumnWidth = 10');
LogStrToFile(FBasName, '                    Columns("T:T").ColumnWidth = 5');
LogStrToFile(FBasName, '                    Columns("U:V").ColumnWidth = 15');
LogStrToFile(FBasName, '                    Columns("W:W").ColumnWidth = 7');
LogStrToFile(FBasName, '                    Columns("X:X").ColumnWidth = 8');
LogStrToFile(FBasName, '                    Columns("Y:AA").ColumnWidth = 15');
LogStrToFile(FBasName, '                Case 5');
LogStrToFile(FBasName, '                    Columns("O:O").ColumnWidth = 20');
LogStrToFile(FBasName, '                    Columns("P:P").ColumnWidth = 15');
LogStrToFile(FBasName, '                    Columns("Q:Q").ColumnWidth = 10');
LogStrToFile(FBasName, '                    Columns("T:T").ColumnWidth = 15');
LogStrToFile(FBasName, '                    Columns("V:V").ColumnWidth = 15');
LogStrToFile(FBasName, '                    Columns("W:W").ColumnWidth = 10');
LogStrToFile(FBasName, '                Case 6');
LogStrToFile(FBasName, '                    Columns("O:O").ColumnWidth = 20');
LogStrToFile(FBasName, '                    Columns("P:P").ColumnWidth = 15');
LogStrToFile(FBasName, '                    Columns("R:S").ColumnWidth = 15');
LogStrToFile(FBasName, '                    Columns("V:V").ColumnWidth = 6');
LogStrToFile(FBasName, '                    Columns("W:W").ColumnWidth = 15');
LogStrToFile(FBasName, '                    Columns("X:X").ColumnWidth = 7');
LogStrToFile(FBasName, '                    Columns("Y:Y").ColumnWidth = 8');
LogStrToFile(FBasName, '                    Columns("Z:AA").ColumnWidth = 15');
LogStrToFile(FBasName, '                    Columns("AC:AB").ColumnWidth = 10');
LogStrToFile(FBasName, '            End Select');
LogStrToFile(FBasName, '            ');
LogStrToFile(FBasName, '            Dim s As String');
LogStrToFile(FBasName, '            ');
LogStrToFile(FBasName, '            s = "A1:" + RightChars(i) + "3"');
LogStrToFile(FBasName, '            Range(s).Borders(xlDiagonalDown).LineStyle = xlNone');
LogStrToFile(FBasName, '            Range(s).Borders(xlDiagonalUp).LineStyle = xlNone');
LogStrToFile(FBasName, '            With Range(s).Borders(xlEdgeLeft)');
LogStrToFile(FBasName, '                .LineStyle = xlContinuous');
LogStrToFile(FBasName, '                .Weight = xlMedium');
LogStrToFile(FBasName, '                .ColorIndex = xlAutomatic');
LogStrToFile(FBasName, '            End With');
LogStrToFile(FBasName, '            With Range(s).Borders(xlEdgeTop)');
LogStrToFile(FBasName, '                .LineStyle = xlContinuous');
LogStrToFile(FBasName, '                .Weight = xlMedium');
LogStrToFile(FBasName, '                .ColorIndex = xlAutomatic');
LogStrToFile(FBasName, '            End With');
LogStrToFile(FBasName, '            With Range(s).Borders(xlEdgeBottom)');
LogStrToFile(FBasName, '                .LineStyle = xlContinuous');
LogStrToFile(FBasName, '                .Weight = xlMedium');
LogStrToFile(FBasName, '                .ColorIndex = xlAutomatic');
LogStrToFile(FBasName, '            End With');
LogStrToFile(FBasName, '            With Range(s).Borders(xlEdgeRight)');
LogStrToFile(FBasName, '                .LineStyle = xlContinuous');
LogStrToFile(FBasName, '                .Weight = xlMedium');
LogStrToFile(FBasName, '                .ColorIndex = xlAutomatic');
LogStrToFile(FBasName, '            End With');
LogStrToFile(FBasName, '            With Range(s).Borders(xlInsideVertical)');
LogStrToFile(FBasName, '                .LineStyle = xlContinuous');
LogStrToFile(FBasName, '                .Weight = xlMedium');
LogStrToFile(FBasName, '                .ColorIndex = xlAutomatic');
LogStrToFile(FBasName, '            End With');
LogStrToFile(FBasName, '            With Range(s).Borders(xlInsideHorizontal)');
LogStrToFile(FBasName, '                .LineStyle = xlContinuous');
LogStrToFile(FBasName, '                .Weight = xlMedium');
LogStrToFile(FBasName, '                .ColorIndex = xlAutomatic');
LogStrToFile(FBasName, '            End With');
LogStrToFile(FBasName, '            Range("A1:R1").Select');
LogStrToFile(FBasName, '        End With');
LogStrToFile(FBasName, '    Next');
LogStrToFile(FBasName, '    Sheets(SheetNames(1)).Select');
LogStrToFile(FBasName, 'End Sub');
